# Preset OpenSSL directories
IF (NOT OPENSSL_ROOT_DIR)
  MESSAGE("-- Setting default OpenSSL Root Directory")
  SET(OPENSSL_ROOT_DIR "/usr/local/opt/openssl")
ENDIF (NOT OPENSSL_ROOT_DIR)

IF (NOT OPENSSL_LIBRARIES)
  MESSAGE("-- Setting default OpenSSL Library Directory")
  SET(OPENSSL_LIBRARIES "/usr/local/opt/openssl/lib")
ENDIF (NOT OPENSSL_LIBRARIES)

MESSAGE("-- OPENSSL ROOT PATH \t" ${OPENSSL_ROOT_DIR})
MESSAGE("-- OPENSSL LIBRARIES \t" ${OPENSSL_LIBRARIES})

IF (NOT CRYPTOPP_LIBRARY_DIR)
  MESSAGE("-- Setting default CRYPTOPP_LIBRARY_DIR Directory")
  SET(CRYPTOPP_LIBRARY_DIR "/usr/local/include/cryptopp")
ENDIF (NOT CRYPTOPP_LIBRARY_DIR)

MESSAGE("-- CRYPTOPP_LIBRARY_DIR PATH \t" ${CRYPTOPP_LIBRARY_DIR})
INCLUDE_DIRECTORIES(${CRYPTOPP_LIBRARY_DIR})
LINK_DIRECTORIES(${CRYPTOPP_LIBRARY_DIR})

IF (NOT CURL_DIR)
  MESSAGE("-- Setting default CURL_DIR Directory")
  SET(CURL_DIR "/usr/local/curl")
ENDIF (NOT CURL_DIR)

MESSAGE("-- CURL_DIR PATH \t" ${CURL_DIR})
INCLUDE_DIRECTORIES(${CURL_DIR})

FIND_PACKAGE(Boost COMPONENTS program_options thread chrono system REQUIRED)
FIND_PACKAGE(cpprestsdk REQUIRED)

INCLUDE_DIRECTORIES(${Boost_INCLUDE_DIR})
MESSAGE("-- BOOST PATH \t\t" ${Boost_INCLUDE_DIR})

SET(
  REQUIRED_LIBRARIES
  cpprestsdk::cpprest
  ${Boost_SYSTEM_LIBRARY}
  ${Boost_PROGRAM_OPTIONS_LIBRARY}
  ${Boost_THREAD_LIBRARY}
  ${Boost_CHRONO_LIBRARY}
)

IF (NOT HSDB_LIBRARY_DIR)
  MESSAGE("-- Setting default HSDB_LIBRARY_DIR Include Directory")
  SET(HSDB_LIBRARY_DIR "${CMAKE_CURRENT_LIST_DIR}/../lib")
ENDIF (NOT HSDB_LIBRARY_DIR)

MESSAGE("-- HSDB_LIBRARY_DIR\t" ${HSDB_LIBRARY_DIR})

INCLUDE_DIRECTORIES(${HSDB_LIBRARY_DIR})
LINK_DIRECTORIES(${HSDB_LIBRARY_DIR})